/* eslint-disable @next/next/no-css-tags */
import BootstrapClient from "@/components/BootstrapClient";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
                <link rel="stylesheet" href="/assets/css/style.css" />
                <link rel="stylesheet" href="/assets/css/responsive.css" />

                <link rel="stylesheet" href="assets/css/remixicon.css" />
                <link rel="stylesheet" href="assets/css/odometer.min.css" />
                <link
                    rel="stylesheet"
                    href="assets/css/swiper-bundle.min.css"
                />
                <link
                    rel="stylesheet"
                    href="assets/css/magnific-popup.min.css"
                />
                <link rel="stylesheet" href="assets/css/owl.carousel.min.css" />
                <link
                    rel="stylesheet"
                    href="assets/css/owl.theme.default.min.css"
                />
                {/* <link rel="stylesheet" href="assets/css/scrollCue.css" /> */}
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <BootstrapClient />
                {children}
            </body>
        </html>
    );
}
